export default [
  "간장",
  "계란",
  "고사리",
  "고추장",
  "당근",
  "도라지",
  "돼지고기",
  "된장",
  "두부",
  "무우",
  "버섯",
  "보리밥",
  "소고기",
  "시금치",
  "쌀밥",
  "쌈장",
  "애호박",
  "양배추",
  "양파",
  "오이",
  "육회",
  "콩나물",
  "표고버섯"
]
// export default [
//   "alfalfa",
//   "almonds",
//   "anchovies",
//   "artichoke",
//   "avocado",
//   "bacon",
//   "basil",
//   "bayleaves",
//   "bbqchicken",
//   "beans",
//   "beef",
//   "beetroot",
//   "bluecheese",
//   "brie",
//   "broccoli",
//   "cajunchicken",
//   "camembert",
//   "capers",
//   "capicolla",
//   "cardamon",
//   "carrot",
//   "cauliflower",
//   "cheddar",
//   "chickenmasala",
//   "chickentikka",
//   "chili",
//   "chives",
//   "chorizo",
//   "cilantro",
//   "colby",
//   "coriander",
//   "crayfish",
//   "cumin",
//   "dill",
//   "duck",
//   "eggplant",
//   "fenugreek",
//   "feta",
//   "fungi",
//   "garlic",
//   "goatcheese",
//   "gorgonzola",
//   "gouda",
//   "ham",
//   "jalapeno",
//   "laurel",
//   "leeks",
//   "lettuce",
//   "limburger",
//   "lobster",
//   "manchego",
//   "marjoram",
//   "meatballs",
//   "melon",
//   "montereyjack",
//   "mozzarella",
//   "muenster",
//   "mushrooms",
//   "olives",
//   "onion",
//   "oregano",
//   "oysters",
//   "parsley",
//   "parmesan",
//   "peanuts",
//   "peas",
//   "pecans",
//   "pepperoni",
//   "peppers",
//   "pineapple",
//   "pinenuts",
//   "pistachios",
//   "prawn",
//   "prosciutto",
//   "provolone",
//   "ricotta",
//   "romano",
//   "roquefort",
//   "rosemary",
//   "salami",
//   "salmon",
//   "sausage",
//   "scallions",
//   "shallots",
//   "shrimp",
//   "snowpeas",
//   "spinach",
//   "squash",
//   "squid",
//   "sweetcorn",
//   "tomatoes",
//   "tuna",
//   "turkey",
//   "venison",
//   "walnuts",
//   "watercress",
//   "whitebait",
//   "zucchini"
// ]